services:
    app:
        image: ultra59/devops-for-developers-project-74
        build:
            context: .
            dockerfile: Dockerfile.production
        command: make test
        depends_on:
            db:
                condition: service_healthy

    db:
        image: postgres:latest
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: password
            POSTGRES_DB: postgres
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U postgres"]
            interval: 5s
            timeout: 5s
            retries: 5
