version: "3.9"

services:
    app:
        image: ultra59/devops-for-developers-project-74
        build:
            context: .
            dockerfile: Dockerfile.production
        command: make test
